// This file is auto-generated by esbuild.config.mjs. Do not edit manually.
import type { WebOSItem } from '../../../types';
import { defaultBrowser } from './browser';
import { widgetChess } from './chess-ai';
import { defaultFinder } from './finder';
import { widgetMiniMD } from './mini-md';
import { widgetPomodoro } from './pomodoro';
import { widgetSnake } from './snake-game';
import { defaultWidgetBtc } from './widget-btc';
import { defaultWidgetCalc } from './widget-calc';
import { defaultWidgetIde } from './widget-ide';
import { defaultWidgetPing } from './widget-ping';
import { defaultWidgetSystem } from './widget-system';
import { defaultWidgetTictactoe } from './widget-tictactoe';
import { defaultWidgetVideo } from './widget-video';
import { defaultYoutube } from './youtube';

/** Default desktop items (apps + inline widgets). */
export const DEFAULT_ITEMS_BASE: WebOSItem[] = [
  defaultBrowser,
  widgetChess,
  defaultFinder,
  widgetMiniMD,
  widgetPomodoro,
  widgetSnake,
  defaultWidgetBtc,
  defaultWidgetCalc,
  defaultWidgetIde,
  defaultWidgetPing,
  defaultWidgetSystem,
  defaultWidgetTictactoe,
  defaultWidgetVideo,
  defaultYoutube,
];
