// This file is auto-generated by esbuild.config.mjs. Do not edit manually.
import type { ComponentType } from 'react';
import type { WebOSAPI } from '../../../types';
import { QuickNoteWidget } from './QuickNoteWidget';
import { VideoWidget } from './VideoWidget';

export type WidgetComponent = ComponentType<{ api: WebOSAPI; instanceId?: string }>;

export const DEFAULT_WIDGET_COMPONENTS: Record<string, WidgetComponent> = {
  'quicknote': QuickNoteWidget,
  'video': VideoWidget,
};

export const normalizeWidgetId = (value: string) =>
  value.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
