import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const generateDefaultWidgetRegistry = () => {
    const defaultsDir = path.join(__dirname, "src", "components", "Widgets", "defaults");
    const registryPath = path.join(defaultsDir, "tsxRegistry.ts");
    if (!fs.existsSync(defaultsDir)) return;
    const files = fs.readdirSync(defaultsDir)
        .filter((file) => file.endsWith(".tsx"));

    const imports = files.map((file) => {
        const base = file.replace(/\.tsx$/, "");
        return `import { ${base} } from './${base}';`;
    });

    const mappings = files.map((file) => {
        const base = file.replace(/\.tsx$/, "");
        const rawId = base.replace(/Widget$/, "");
        const normalized = rawId.replace(/[^a-zA-Z0-9]/g, "").toLowerCase();
        return `  '${normalized}': ${base},`;
    });

    const content = `// This file is auto-generated by esbuild.config.mjs. Do not edit manually.
import type { ComponentType } from 'react';
import type { WebOSAPI } from '../../../types';
${imports.join("\n")}

export type WidgetComponent = ComponentType<{ api: WebOSAPI; instanceId?: string }>;

export const DEFAULT_WIDGET_COMPONENTS: Record<string, WidgetComponent> = {
${mappings.join("\n")}
};

export const normalizeWidgetId = (value: string) =>
  value.replace(/[^a-zA-Z0-9]/g, '').toLowerCase();
`;

    fs.writeFileSync(registryPath, content, "utf8");
};

const generateDefaultItemsRegistry = () => {
    const defaultsDir = path.join(__dirname, "src", "components", "Widgets", "defaults");
    const registryPath = path.join(defaultsDir, "defaultsRegistry.ts");
    if (!fs.existsSync(defaultsDir)) return;

    const files = fs.readdirSync(defaultsDir)
        .filter((file) =>
            file.endsWith(".ts") &&
            file !== "index.ts" &&
            file !== "tsxRegistry.ts" &&
            file !== "defaultsRegistry.ts" &&
            !file.endsWith(".generated.ts")
        )
        .sort();

    const entries = [];
    for (const file of files) {
        const fullPath = path.join(defaultsDir, file);
        const content = fs.readFileSync(fullPath, "utf8");
        const match = content.match(/export\s+const\s+([a-zA-Z0-9_]+)/);
        if (!match) continue;
        entries.push({ name: match[1], file: file.replace(/\.ts$/, "") });
    }

    const imports = entries.map((entry) => `import { ${entry.name} } from './${entry.file}';`);
    const items = entries.map((entry) => `  ${entry.name},`);

    const content = `// This file is auto-generated by esbuild.config.mjs. Do not edit manually.
import type { WebOSItem } from '../../../types';
${imports.join("\n")}

/** Default desktop items (apps + inline widgets). */
export const DEFAULT_ITEMS_BASE: WebOSItem[] = [
${items.join("\n")}
];
`;

    fs.writeFileSync(registryPath, content, "utf8");
};

/** Extract a double-quoted string value (with \\ and \\n escapes) from JSON-like content after key. */
function extractString(content, key) {
    const marker = `"${key}": "`;
    const start = content.indexOf(marker);
    if (start === -1) return null;
    let i = start + marker.length;
    let out = "";
    while (i < content.length) {
        const c = content[i];
        if (c === "\\") {
            const next = content[i + 1];
            if (next === "n") { out += "\n"; i += 2; }
            else if (next === '"') { out += '"'; i += 2; }
            else { out += c + (next || ""); i += 2; }
            continue;
        }
        if (c === '"') break;
        out += c;
        i++;
    }
    return out;
}

/** Generate widget-kanban-content from obsidian-obsidget-ts kanban-pro if present. */
function generateKanbanContent() {
    const defaultsDir = path.join(__dirname, "src", "components", "Widgets", "defaults");
    const kanbanProPath = path.join(__dirname, "..", "obsidian-obsidget-ts", "gallery", "kanban-pro.tsx");
    const outPath = path.join(defaultsDir, "widget-kanban-content.generated.ts");
    const escapeForTemplate = (s) => s.replace(/\$\{/g, "\\${").replace(/`/g, "\\`");
    if (!fs.existsSync(kanbanProPath)) {
        const fallback = `// Kanban Pro source not found; using minimal fallback.
export const html = "<div class=\\"kanban-wrapper\\" id=\\"kanban-root\\"><div class=\\"kanban-board\\"><div class=\\"kanban-column\\" data-state=\\"todo\\"><div class=\\"kanban-column-items\\" data-state=\\"todo\\"></div></div><div class=\\"kanban-column\\" data-state=\\"in-progress\\"><div class=\\"kanban-column-items\\" data-state=\\"in-progress\\"></div></div><div class=\\"kanban-column\\" data-state=\\"done\\"><div class=\\"kanban-column-items\\" data-state=\\"done\\"></div></div></div></div>";
export const css = ".kanban-wrapper{display:flex;flex-direction:column;height:100%;}";
export const js = "if(typeof api!=='undefined'&&api.root){api.root.innerHTML='<p>Kanban Pro source missing. Build with obsidian-obsidget-ts in sibling folder.</p>';}";
`;
        fs.writeFileSync(outPath, fallback, "utf8");
        return;
    }
    const content = fs.readFileSync(kanbanProPath, "utf8");
    const html = extractString(content, "html");
    const css = extractString(content, "css");
    const js = extractString(content, "js");
    if (!html || !css || !js) {
        fs.writeFileSync(outPath, "export const html=\"\"; export const css=\"\"; export const js=\"\";", "utf8");
        return;
    }
    const ts = `// Auto-generated from obsidian-obsidget-ts/gallery/kanban-pro.tsx
export const html = \`${escapeForTemplate(html)}\`;
export const css = \`${escapeForTemplate(css)}\`;
export const js = \`${escapeForTemplate(js)}\`;
`;
    fs.writeFileSync(outPath, ts, "utf8");
}

const generateWidgetsPlugin = {
    name: "generate-default-widgets",
    setup(build) {
        build.onStart(() => {
            generateKanbanContent();
            generateDefaultWidgetRegistry();
            generateDefaultItemsRegistry();
        });
    }
};

const context = await esbuild.context({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        ...builtins,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    plugins: [generateWidgetsPlugin],
    outfile: "main.js",
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}